version: '3.7'

services:

  postgres:
   image: postgres:latest
   container_name: postgres
   restart: always
   networks:
           tools_network:
               ipv4_address: 172.25.1.1
   ports:
     - "5432:5432"
   environment:    
     POSTGRES_PASSWORD: postgres
     POSTGRES_USER: postgres


  pgAdmin4:
   image: dpage/pgadmin4:latest
   container_name: pgAdmin4
   restart: always
   networks:
            tools_network:
                ipv4_address: 172.25.1.2
   ports:
    - "16543:80"
   depends_on:
    - postgres
   environment:
    PGADMIN_DEFAULT_EMAIL: "admin@sandbox.com"
    PGADMIN_DEFAULT_PASSWORD: "postgres"





  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
   container_name: elasticsearch
   restart: always
   networks:
            tools_network:
                ipv4_address: 172.25.1.3
   ports:
    - "9200:9200"
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data


  kibana:
   image: docker.elastic.co/kibana/kibana:6.2.4
   container_name: kibana
   restart: always
   networks:
            tools_network:
                ipv4_address: 172.25.1.4
   ports:
    - "5601:5601"
   depends_on:
    - elasticsearch





  minio-node-1:
   image: minio/minio:RELEASE.2019-09-25T18-25-51Z
   container_name: minio-node-1
   restart: always
   networks:
            tools_network:
                ipv4_address: 172.25.1.5
   volumes:
    - minio-node-1-data:/data
   environment:
    MINIO_ACCESS_KEY: minio
    MINIO_SECRET_KEY: minio123
   command: server http://172.25.1.5/data http://172.25.1.6/data http://172.25.1.7/data http://172.25.1.8/data 
 

  minio-node-2:
   image: minio/minio:RELEASE.2019-09-25T18-25-51Z
   container_name: minio-node-2
   restart: always
   networks:
            tools_network:
                ipv4_address: 172.25.1.6
   volumes:
    - minio-node-2-data:/data
   environment:
    MINIO_ACCESS_KEY: minio
    MINIO_SECRET_KEY: minio123
   command: server http://172.25.1.5/data http://172.25.1.6/data http://172.25.1.7/data http://172.25.1.8/data
 

  minio-node-3:
   image: minio/minio:RELEASE.2019-09-25T18-25-51Z
   container_name: minio-node-3
   restart: always
   networks:
            tools_network:
                ipv4_address: 172.25.1.7
   volumes:
    - minio-node-3-data:/data
   environment:
    MINIO_ACCESS_KEY: minio
    MINIO_SECRET_KEY: minio123
   command: server http://172.25.1.5/data http://172.25.1.6/data http://172.25.1.7/data http://172.25.1.8/data 
 

  minio-node-4:
   image: minio/minio:RELEASE.2019-09-25T18-25-51Z
   container_name: minio-node-4
   restart: always
   networks:
            tools_network:
                ipv4_address: 172.25.1.8
   volumes:
    - minio-node-4-data:/data
   environment:
    MINIO_ACCESS_KEY: minio
    MINIO_SECRET_KEY: minio123
   command: server http://172.25.1.5/data http://172.25.1.6/data http://172.25.1.7/data http://172.25.1.8/data





  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: always
    networks:
            tools_network:
                ipv4_address: 172.25.1.9
    ports:
      - "8080:8080"   # Frontend HAProxy
      - "9000:9000"   # Frontend and Backend MinIO
    links:
      - minio-node-1
      - minio-node-2
      - minio-node-3
      - minio-node-4
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg


networks:
    tools_network:
        name: tools_network
        ipam:
            driver: default
            config:
                - subnet: 172.25.0.0/16



volumes:
  elasticsearch-data:
  minio-node-1-data:
  minio-node-2-data:
  minio-node-3-data:
  minio-node-4-data: