version: '3.4'

services:

  postgres:
   image: postgres:latest
   container_name: postgres
   restart: always
   networks:
           tools_network:
               ipv4_address: 172.25.1.1
   ports:
     - "5432:5432"
   environment:    
     POSTGRES_PASSWORD: postgres
     POSTGRES_USER: postgres





  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
   container_name: elasticsearch
   restart: always
   networks:
            tools_network:
                ipv4_address: 172.25.1.2
   ports:
    - "9200:9200"
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data


  kibana:
   image: docker.elastic.co/kibana/kibana:6.2.4
   container_name: kibana
   restart: always
   networks:
            tools_network:
                ipv4_address: 172.25.1.3
   ports:
    - "5601:5601"
   depends_on:
    - elasticsearch





  minio-node-1:
   image: minio/minio:RELEASE.2019-04-18T01-15-57Z
   container_name: minio-node-1
   restart: always
   networks:
            tools_network:
                ipv4_address: 172.25.1.4
   ports:
    - "9001:9000"
   volumes:
    - minio-node-1-data:/data
   environment:
    MINIO_ACCESS_KEY: minio
    MINIO_SECRET_KEY: minio123
   command: server http://172.25.1.4/data http://172.25.1.5/data http://172.25.1.6/data http://172.25.1.7/data 
 

  minio-node-2:
   image: minio/minio:RELEASE.2019-04-18T01-15-57Z
   container_name: minio-node-2
   restart: always
   networks:
            tools_network:
                ipv4_address: 172.25.1.5
   ports:
    - "9002:9000"
   volumes:
    - minio-node-2-data:/data
   environment:
    MINIO_ACCESS_KEY: minio
    MINIO_SECRET_KEY: minio123
   command: server http://172.25.1.4/data http://172.25.1.5/data http://172.25.1.6/data http://172.25.1.7/data 
 

  minio-node-3:
   image: minio/minio:RELEASE.2019-04-18T01-15-57Z
   container_name: minio-node-3
   restart: always
   networks:
            tools_network:
                ipv4_address: 172.25.1.6
   ports:
    - "9003:9000"
   volumes:
    - minio-node-3-data:/data
   environment:
    MINIO_ACCESS_KEY: minio
    MINIO_SECRET_KEY: minio123
   command: server http://172.25.1.4/data http://172.25.1.5/data http://172.25.1.6/data http://172.25.1.7/data 
 

  minio-node-4:
   image: minio/minio:RELEASE.2019-04-18T01-15-57Z
   container_name: minio-node-4
   restart: always
   networks:
            tools_network:
                ipv4_address: 172.25.1.7
   ports:
    - "9004:9000"
   volumes:
    - minio-node-4-data:/data
   environment:
    MINIO_ACCESS_KEY: minio
    MINIO_SECRET_KEY: minio123
   command: server http://172.25.1.4/data http://172.25.1.5/data http://172.25.1.6/data http://172.25.1.7/data 



networks:
    tools_network:
        ipam:
            driver: default
            config:
                - subnet: 172.25.0.0/16



volumes:
  elasticsearch-data:
  minio-node-1-data:
  minio-node-2-data:
  minio-node-3-data:
  minio-node-4-data: