version: '3.7'

services:

  tradeunioncommittee.react.web.gui:
    image: tradeunioncommittee_react_web_gui
    container_name: tradeunioncommittee_react_web_gui
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.25.1.1
    ports:
      - "8500:3000"
    build:
      context: .
      dockerfile: doc.React.Web.GUI.dockerfile
    environment:
      - NODE_ENV=production
      - REACT_APP_MAIN_API_URL=http://localhost:8510/api/



  tradeunioncommittee.api:
    image: tradeunioncommittee_api
    container_name: tradeunioncommittee_api
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.25.1.2
    ports:
      - "8510:80"
      - "8515:443"
    volumes:
      - ./appsettings.api.json:/app/appsettings.json
    build:
      context: .
      dockerfile: doc.Api.dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80



  tradeunioncommittee.data.analysis.api:
    image: tradeunioncommittee_data_analysis_api
    container_name: tradeunioncommittee_data_analysis_api
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.25.1.3
    ports:
      - "8520:5000"
    build:
      context: .
      dockerfile: doc.DataAnalysis.Api.dockerfile



  tradeunioncommittee.razor.web.gui:
    image: tradeunioncommittee_razor_web_gui
    container_name: tradeunioncommittee_razor_web_gui
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.25.1.4
    ports:
      - "8530:80"
      - "8535:443"
    volumes:
      - ./appsettings.razor.web.gui.json:/app/appsettings.json
    build:
      context: .
      dockerfile: doc.Razor.Web.GUI.dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80



  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.25.1.7
    ports:
      - "5432:5432"
    environment:    
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data



  pgAdmin4:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin4
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.25.1.8
    ports:
      - "15432:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@sandbox.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    volumes:
      - pgAdmin4-data:/var/lib/pgadmin



  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.25.1.9
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data



  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.25.1.10
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch



  minio-n01:
    image: minio/minio:RELEASE.2020-05-16T01-33-21Z
    container_name: minio-n01
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.25.1.12
    volumes:
      - minio-n01-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio-n01/data http://minio-n02/data http://minio-n03/data http://minio-n04/data



  minio-n02:
    image: minio/minio:RELEASE.2020-05-16T01-33-21Z
    container_name: minio-n02
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.25.1.13
    volumes:
      - minio-n02-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio-n01/data http://minio-n02/data http://minio-n03/data http://minio-n04/data



  minio-n03:
    image: minio/minio:RELEASE.2020-05-16T01-33-21Z
    container_name: minio-n03
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.25.1.14
    volumes:
      - minio-n03-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio-n01/data http://minio-n02/data http://minio-n03/data http://minio-n04/data



  minio-n04:
    image: minio/minio:RELEASE.2020-05-16T01-33-21Z
    container_name: minio-n04
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.25.1.15
    volumes:
      - minio-n04-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio-n01/data http://minio-n02/data http://minio-n03/data http://minio-n04/data



  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.25.1.16
    ports:
      - "8080:8080"   # Frontend HAProxy
      - "9000:9000"   # Frontend and Backend MinIO
    links:
      - minio-n01
      - minio-n02
      - minio-n03
      - minio-n04
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg



networks:
    tradeunioncommittee_network:
        name: tradeunioncommittee_network
        ipam:
            driver: default
            config:
                - subnet: 172.25.0.0/16



volumes:
  postgres-data:
  pgAdmin4-data:
  elasticsearch-data:
  minio-n01-data:
  minio-n02-data:
  minio-n03-data:
  minio-n04-data: