version: '3.4'

services:

  tradeunioncommittee.api:
    image: ${DOCKER_REGISTRY-}tradeunioncommittee_api
    container_name: tradeunioncommittee_api
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.28.1.2
    ports:
      - "8510:80"
      - "8515:443"
    build:
      context: .
      dockerfile: TradeUnionCommittee.Api/src/TradeUnionCommittee.Api/Dockerfile



  tradeunioncommittee.data.analysis.api:
    image: ${DOCKER_REGISTRY-}tradeunioncommittee_data_analysis_api
    container_name: tradeunioncommittee_data_analysis_api
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.28.1.3
    ports:
      - "8520:5000"
    build:
      context: .
      dockerfile: TradeUnionCommittee.DataAnalysis.Api/src/TradeUnionCommittee.DataAnalysis.Api/Dockerfile



  tradeunioncommittee.razor.web.gui:
    image: ${DOCKER_REGISTRY-}tradeunioncommittee_razor_web_gui
    container_name: tradeunioncommittee_razor_web_gui
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.28.1.4
    ports:
      - "8530:80"
      - "8535:443"
    build:
      context: .
      dockerfile: TradeUnionCommittee.Razor.Web.GUI/src/TradeUnionCommittee.Razor.Web.GUI/Dockerfile



  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.28.1.7
    ports:
      - "5432:5432"
    environment:    
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres



  pgAdmin4:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin4
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.28.1.8
    ports:
      - "16543:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "stewie.griffin@test.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"



  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.28.1.9
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data



  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.28.1.10
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch



  minio-node-1:
    image: minio/minio:RELEASE.2019-09-25T18-25-51Z
    container_name: minio-node-1
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.28.1.13
    ports:
      - "9001:9000"
    volumes:
      - minio-node-1-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://172.28.1.13/data http://172.28.1.14/data http://172.28.1.15/data http://172.28.1.16/data



  minio-node-2:
    image: minio/minio:RELEASE.2019-09-25T18-25-51Z
    container_name: minio-node-2
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.28.1.14
    ports:
      - "9002:9000"
    volumes:
      - minio-node-2-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://172.28.1.13/data http://172.28.1.14/data http://172.28.1.15/data http://172.28.1.16/data



  minio-node-3:
    image: minio/minio:RELEASE.2019-09-25T18-25-51Z
    container_name: minio-node-3
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.28.1.15
    ports:
      - "9003:9000"
    volumes:
      - minio-node-3-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://172.28.1.13/data http://172.28.1.14/data http://172.28.1.15/data http://172.28.1.16/data



  minio-node-4:
    image: minio/minio:RELEASE.2019-09-25T18-25-51Z
    container_name: minio-node-4
    restart: always
    networks:
            tradeunioncommittee_network:
                ipv4_address: 172.28.1.16
    ports:
      - "9004:9000"
    volumes:
      - minio-node-4-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://172.28.1.13/data http://172.28.1.14/data http://172.28.1.15/data http://172.28.1.16/data



networks:
    tradeunioncommittee_network:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16



volumes:
  elasticsearch-data:
  minio-node-1-data:
  minio-node-2-data:
  minio-node-3-data:
  minio-node-4-data: